version: '3.6'

services:
  postgres:
    container_name: postgres
    image: postgres:15.0
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file:
      - ./.env
    networks:
      - postgres

  pgadmin:
    links:
      - postgres:postgres
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - "8082:80"
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file:
      - ./.env
    networks:
      - postgres


networks:
  postgres:
    driver: bridge

volumes:
  data:
  pgadmin:
  postgres:
